.TH KALI-SERVER-MCP "1" "February 2026" "kali-server-mcp 0.0~git20260119.bffe9f2" "User Commands"
.SH NAME
kali-server-mcp \- Kali Linux MCP API Server
.SH DESCRIPTION
usage: kali-server-mcp [\-h] [\-\-debug] [\-\-port PORT] [\-\-ip IP]
.PP
Run the Kali Linux API Server
.SS "options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-debug\fR
Enable debug mode
.TP
\fB\-\-port\fR PORT
Port for the API server (default: 5000)
.TP
\fB\-\-ip\fR IP
IP address to bind the server to (default: 127.0.0.1 for
localhost only)
